version: "2"
linters:
  default: all
  disable:
    - varnamelen
    - revive
    - lll
    - gosmopolitan
    - contextcheck
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - forbidigo
    - funlen
    - ireturn
    - prealloc
    - testifylint
    - gosec
    - paralleltest
  exclusions:
    paths-except:
      - "ent"
