// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/katsukiniwa/go-ent-mysql/product/ent/predicate"
	"github.com/katsukiniwa/go-ent-mysql/product/ent/product"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks     []Hook
	mutation  *ProductMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStock sets the "stock" field.
func (_u *ProductUpdate) SetStock(v int) *ProductUpdate {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableStock(v *int) *ProductUpdate {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *ProductUpdate) AddStock(v int) *ProductUpdate {
	_u.mutation.AddStock(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProductUpdate) SetTitle(v string) *ProductUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableTitle(v *string) *ProductUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSaleStatus sets the "sale_status" field.
func (_u *ProductUpdate) SetSaleStatus(v product.SaleStatus) *ProductUpdate {
	_u.mutation.SetSaleStatus(v)
	return _u
}

// SetNillableSaleStatus sets the "sale_status" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSaleStatus(v *product.SaleStatus) *ProductUpdate {
	if v != nil {
		_u.SetSaleStatus(*v)
	}
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdate) Mutation() *ProductMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdate) check() error {
	if v, ok := _u.mutation.Stock(); ok {
		if err := product.StockValidator(v); err != nil {
			return &ValidationError{Name: "stock", err: fmt.Errorf(`ent: validator failed for field "Product.stock": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SaleStatus(); ok {
		if err := product.SaleStatusValidator(v); err != nil {
			return &ValidationError{Name: "sale_status", err: fmt.Errorf(`ent: validator failed for field "Product.sale_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SaleStatus(); ok {
		_spec.SetField(product.FieldSaleStatus, field.TypeEnum, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProductMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetStock sets the "stock" field.
func (_u *ProductUpdateOne) SetStock(v int) *ProductUpdateOne {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableStock(v *int) *ProductUpdateOne {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *ProductUpdateOne) AddStock(v int) *ProductUpdateOne {
	_u.mutation.AddStock(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProductUpdateOne) SetTitle(v string) *ProductUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableTitle(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSaleStatus sets the "sale_status" field.
func (_u *ProductUpdateOne) SetSaleStatus(v product.SaleStatus) *ProductUpdateOne {
	_u.mutation.SetSaleStatus(v)
	return _u
}

// SetNillableSaleStatus sets the "sale_status" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSaleStatus(v *product.SaleStatus) *ProductUpdateOne {
	if v != nil {
		_u.SetSaleStatus(*v)
	}
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdateOne) Mutation() *ProductMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Product entity.
func (_u *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdateOne) check() error {
	if v, ok := _u.mutation.Stock(); ok {
		if err := product.StockValidator(v); err != nil {
			return &ValidationError{Name: "stock", err: fmt.Errorf(`ent: validator failed for field "Product.stock": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SaleStatus(); ok {
		if err := product.SaleStatusValidator(v); err != nil {
			return &ValidationError{Name: "sale_status", err: fmt.Errorf(`ent: validator failed for field "Product.sale_status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ProductUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(product.FieldStock, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SaleStatus(); ok {
		_spec.SetField(product.FieldSaleStatus, field.TypeEnum, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Product{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
