name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Copy .env
        run: |
          cp .env.example .env
      - name: Check
        run: |
          docker compose up --build -d
          docker compose exec app make build
